In [1]:
from torchsummary import summary
from python_lib.BasicModel import BasicModel
import torch
import numpy as np

In [2]:
model = BasicModel(input_size = 2, input_length = 16, out_features = 6).to("cuda")
# summary(model, (2,16))

# input_feats = torch.rand([10,2,16]).to("cuda")
# output = model(input_feats)
# output.shape

In [3]:
input_feats = torch.rand([1,2,16]).to("cuda")
output = model(input_feats)
output.shape

tensor([[[-0.4062, -0.4062, -0.4062, -0.4062, -0.4062, -0.4062, -0.4062,
          -0.4062, -0.4062,  2.4408,  2.4336, -0.4062, -0.4062, -0.4062],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [-0.4838, -0.4838, -0.4838,  2.6054, -0.4838,  0.7058,  2.0109,
          -0.4838, -0.4838, -0.4838, -0.4838, -0.4838, -0.4838, -0.4838],
         [ 1.3542, -1.2284,  0.0256,  0.2477, -1.2284,  1.3138, -0.6918,
          -1.0874,  1.1860, -0.1399, -0.0590, -0.2233, -1.1609,  1.6918]]],
       device='cuda:0', grad_fn=<CudnnBatchNormBackward0>)


c:\Users\chiny\OneDrive - Nanyang Technological University\Internships\AY24 DSO Summer\LegacyCNN\python_lib\BasicModel.py:73: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  z = F.softmax(y)


torch.Size([1, 6])

In [4]:
model.save("BasicModelWeights")

In [5]:
inputs = np.array([
    [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
    [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7]
], dtype= np.float32)

inputs = torch.from_numpy(inputs).to("cuda")
inputs  = torch.reshape(inputs, (1,2,16))
inputs.shape
model(inputs)

tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [-0.8139, -0.3124,  1.8746, -0.3729, -0.8139, -0.3124,  1.8746,
          -0.3729, -0.8139, -0.3124,  1.8746, -0.3729, -0.8139, -0.3124],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]],
       device='cuda:0', grad_fn=<CudnnBatchNormBackward0>)


tensor([[0.1685, 0.0557, 0.3693, 0.1538, 0.0570, 0.1958]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)