In [1]:
from torchsummary import summary
from python_lib.BasicModel import BasicModel
import torch
import numpy as np
import os

In [2]:
model = BasicModel(input_size = 2, input_length = 16, out_features = 6).to("cuda")
# summary(model, (2,16))

# input_feats = torch.rand([10,2,16]).to("cuda")
# output = model(input_feats)
# output.shape

In [3]:
input_feats = torch.rand([1,2,16]).to("cuda")
input_feats_np = input_feats.cpu().detach().numpy()
input_feats_np = np.reshape(input_feats_np, (2,16))
print(input_feats_np)
dim = input_feats_np.shape

flatten_inputs = input_feats_np.flatten()
with open(os.path.join("BasicModelWeights", f"input.bin"), "wb") as f:
            # Write the dimensions down
            f.write(np.array(dim, dtype=np.int32).tobytes())
            # Write the flatten bias down
            f.write(flatten_inputs.tobytes())

[[0.5250837  0.73876137 0.02586478 0.69667655 0.9010054  0.16148174
  0.05709535 0.86704534 0.3937961  0.7966461  0.7111978  0.89118266
  0.22711879 0.94800013 0.60269016 0.72342044]
 [0.11573368 0.9300387  0.94015527 0.0944708  0.983776   0.7164195
  0.97746515 0.25156945 0.6112121  0.3106951  0.20829374 0.9994052
  0.27469456 0.12491971 0.5240147  0.37950414]]


In [4]:
model.layer0(input_feats).cpu().detach().numpy()

array([[[-0.261763  , -0.261763  , -0.261763  , -0.261763  ,
         -0.261763  , -0.261763  , -0.261763  , -0.261763  ,
         -0.261763  , -0.261763  , -0.261763  , -0.261763  ,
         -0.261763  ,  3.402919  ],
        [-0.2556397 , -0.2556397 , -0.2556397 , -0.2556397 ,
          3.3233159 , -0.2556397 , -0.2556397 , -0.2556397 ,
         -0.2556397 , -0.2556397 , -0.2556397 , -0.2556397 ,
         -0.2556397 , -0.2556397 ],
        [-1.074456  , -0.6625108 ,  2.0874026 , -1.074456  ,
         -1.0160321 , -0.20012164, -0.18600944,  0.08975121,
          0.05353802,  1.960633  , -1.074456  ,  0.859243  ,
          0.15582895,  0.08164499],
        [-1.3025054 , -0.2853931 , -1.4954153 , -0.6167996 ,
          0.1824062 , -1.7288157 , -0.24249575,  0.6191411 ,
          0.7942382 ,  0.32387277,  0.1897296 ,  1.9281856 ,
          0.42595991,  1.2078894 ]]], dtype=float32)

In [5]:
model.layer0[0].weight

Parameter containing:
tensor([[[ 0.3313,  0.0343, -0.0220],
         [-0.2709, -0.2457, -0.2315]],

        [[ 0.1394, -0.3578, -0.3096],
         [ 0.2205,  0.2271, -0.0293]],

        [[ 0.0485,  0.0600,  0.4062],
         [ 0.0693, -0.0823,  0.2017]],

        [[ 0.3365,  0.0685, -0.1733],
         [ 0.0222, -0.3500, -0.2283]]], device='cuda:0', requires_grad=True)

In [6]:
model.layer0[0].bias

Parameter containing:
tensor([-0.0333, -0.3720, -0.2758,  0.3628], device='cuda:0',
       requires_grad=True)

In [7]:
model.save("BasicModelWeights")

In [8]:
model(input_feats)

layer0 tensor([[[-0.2618, -0.2618, -0.2618, -0.2618, -0.2618, -0.2618, -0.2618,
          -0.2618, -0.2618, -0.2618, -0.2618, -0.2618, -0.2618,  3.4029],
         [-0.2556, -0.2556, -0.2556, -0.2556,  3.3233, -0.2556, -0.2556,
          -0.2556, -0.2556, -0.2556, -0.2556, -0.2556, -0.2556, -0.2556],
         [-1.0745, -0.6625,  2.0874, -1.0745, -1.0160, -0.2001, -0.1860,
           0.0898,  0.0535,  1.9606, -1.0745,  0.8592,  0.1558,  0.0816],
         [-1.3025, -0.2854, -1.4954, -0.6168,  0.1824, -1.7288, -0.2425,
           0.6191,  0.7942,  0.3239,  0.1897,  1.9282,  0.4260,  1.2079]]],
       device='cuda:0', grad_fn=<CudnnBatchNormBackward0>)
layer1 tensor([[[-0.5192, -0.5192, -0.4364,  3.0999,  0.0465, -0.3307,  0.0099,
          -0.5192, -0.5192, -0.4959,  0.7027, -0.5192],
         [ 0.0597, -0.4958, -0.4958,  3.0588,  0.8810, -0.3017, -0.4958,
          -0.4958, -0.4958, -0.4958, -0.2272, -0.4958],
         [-0.3955, -0.3955,  3.1793, -0.3955,  0.6433, -0.2630, -0.3955,
      

c:\Users\chiny\OneDrive - Nanyang Technological University\Internships\AY24 DSO Summer\LegacyCNN\python_lib\BasicModel.py:77: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  z = F.softmax(y)


tensor([[0.1737, 0.1173, 0.1011, 0.1700, 0.2441, 0.1938]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)

In [9]:
print(model.layer3[0].weight)
print(model.layer3[0].bias)

Parameter containing:
tensor([[[-0.2385,  0.2430,  0.0093],
         [ 0.2713, -0.1681, -0.0315],
         [-0.0668, -0.1337,  0.1041],
         [ 0.2388,  0.2851, -0.0823]],

        [[-0.1117, -0.1278,  0.0092],
         [-0.1055, -0.0316,  0.0143],
         [-0.2109, -0.1395, -0.2807],
         [ 0.1741,  0.2768,  0.1269]],

        [[-0.2697, -0.2338, -0.1891],
         [-0.2268,  0.2445, -0.2594],
         [ 0.0892, -0.2686, -0.2359],
         [-0.0948, -0.0993,  0.1968]],

        [[-0.0365, -0.0223, -0.0142],
         [-0.1873,  0.2537,  0.2415],
         [ 0.2334, -0.1484, -0.0827],
         [ 0.0470,  0.2390, -0.2096]]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 0.1570, -0.2493, -0.0283,  0.2360], device='cuda:0',
       requires_grad=True)


In [10]:
model.layer0

Sequential(
  (0): Conv1d(2, 4, kernel_size=(3,), stride=(1,))
  (1): ReLU(inplace=True)
  (2): BatchNorm1d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)