In [1]:
from torchsummary import summary
from python_lib.BasicModel import BasicModel
import torch
import numpy as np
import os

In [2]:
model = BasicModel(input_size = 2, input_length = 16, out_features = 6).to("cuda")
# summary(model, (2,16))

# input_feats = torch.rand([10,2,16]).to("cuda")
# output = model(input_feats)
# output.shape

In [14]:
input_feats = torch.rand([1,2,16]).to("cuda")
input_feats_np = input_feats.cpu().detach().numpy()
input_feats_np = np.reshape(input_feats_np, (2,16))
print(input_feats_np)
dim = input_feats_np.shape

flatten_inputs = input_feats_np.flatten()
with open(os.path.join("BasicModelWeights", f"input.bin"), "wb") as f:
            # Write the dimensions down
            f.write(np.array(dim, dtype=np.int32).tobytes())
            # Write the flatten bias down
            f.write(flatten_inputs.tobytes())

[[0.36116892 0.97199637 0.12340093 0.9194393  0.39304084 0.8277006
  0.5037204  0.22252554 0.0496543  0.6274032  0.7627669  0.16854572
  0.02383888 0.3918898  0.4734081  0.8415596 ]
 [0.6984848  0.88315094 0.20246547 0.9639936  0.3829733  0.9199399
  0.20050651 0.8582331  0.5207251  0.6750164  0.8634124  0.687095
  0.54691285 0.72526723 0.32679993 0.69680685]]


In [13]:
model.save("BasicModelWeights")

In [16]:
model(input_feats)

layer0 tensor([[[-0.8671,  0.0539, -0.2658, -0.2929, -0.9227, -0.1262, -1.1866,
           1.3479,  1.4074, -1.2795, -1.2375,  1.2374,  0.9331,  1.1986],
         [-0.3747, -0.3747,  3.1981, -0.3747, -0.3747, -0.3747, -0.3747,
          -0.3747,  1.2980, -0.3747, -0.3747, -0.3747, -0.3747, -0.3747],
         [-0.2750,  3.5745, -0.2750, -0.2750, -0.2750, -0.2750, -0.2750,
          -0.2750, -0.2750, -0.2750, -0.2750, -0.2750, -0.2750, -0.2750],
         [-0.2294, -0.2294, -0.2294, -0.2294, -0.2294, -0.2294, -0.2294,
          -0.2294,  2.9828, -0.2294, -0.2294, -0.2294, -0.2294, -0.2294]]],
       device='cuda:0', grad_fn=<CudnnBatchNormBackward0>)
layer1 tensor([[[-1.0905e+00, -1.0905e+00,  1.5498e+00, -3.4352e-01, -8.2475e-01,
           5.8173e-01,  1.6765e+00, -1.0905e+00, -7.4101e-01,  1.0291e+00,
           6.2735e-01, -2.8363e-01],
         [ 2.0433e+00, -6.5909e-01,  2.9850e-01, -7.6984e-01, -7.6984e-01,
          -5.2271e-01,  1.9863e+00, -7.6984e-01, -2.0572e-01, -7.6984e-01,


tensor([[0.0678, 0.0842, 0.1407, 0.1927, 0.2252, 0.2894]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)

In [11]:
print(model.layer0[0].weight)
print(model.layer0[0].bias)

Parameter containing:
tensor([[[-0.3991, -0.0366,  0.0883],
         [ 0.0728, -0.2744,  0.0778]],

        [[-0.3005,  0.1056, -0.1360],
         [-0.0025,  0.3324,  0.2506]],

        [[ 0.3298, -0.3972, -0.0508],
         [-0.1937, -0.3503, -0.0351]],

        [[-0.2671,  0.0069,  0.2288],
         [-0.3560, -0.1769,  0.3855]]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 0.3970, -0.3558,  0.1439, -0.1756], device='cuda:0',
       requires_grad=True)


In [10]:
model.layer0

Sequential(
  (0): Conv1d(2, 4, kernel_size=(3,), stride=(1,))
  (1): ReLU(inplace=True)
  (2): BatchNorm1d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)