In [1]:
from torchsummary import summary
from python_lib.BasicModel import BasicModel
import torch
import numpy as np

In [25]:
model = BasicModel(input_size = 2, input_length = 16, out_features = 6).to("cuda")
# summary(model, (2,16))

# input_feats = torch.rand([10,2,16]).to("cuda")
# output = model(input_feats)
# output.shape

In [52]:
input_feats = torch.rand([1,2,16]).to("cuda")
input_feats.cpu().detach().numpy()

array([[[0.9430284 , 0.11093402, 0.5329974 , 0.69882184, 0.8940353 ,
         0.0047369 , 0.9686028 , 0.27977622, 0.25979286, 0.477512  ,
         0.02473438, 0.39013845, 0.5221011 , 0.89566046, 0.4136904 ,
         0.82651144],
        [0.7341754 , 0.6737632 , 0.8890436 , 0.07677811, 0.85111696,
         0.59205663, 0.49497455, 0.83626556, 0.995208  , 0.86247855,
         0.02370811, 0.17113733, 0.4207794 , 0.16149592, 0.83722293,
         0.45872283]]], dtype=float32)

In [51]:
model.layer0(input_feats).cpu().detach().numpy()

array([[[-0.28379035,  1.1421643 , -1.2283012 ,  0.18014047,
          0.12849443, -0.7908957 , -0.16820729,  1.3845938 ,
         -1.0890554 ,  1.8317938 ,  0.73670846,  0.612956  ,
         -1.2283012 , -1.2283012 ],
        [-0.39602134, -0.39602134, -0.39602134,  1.733568  ,
         -0.39602134, -0.39602134, -0.39602134, -0.39602134,
         -0.39602134, -0.39602134, -0.39602134, -0.37179995,
          2.9944665 , -0.39602134],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-0.81668603,  1.5080918 ,  0.02670713, -0.81668603,
          0.49627864,  0.83826894, -0.81668603, -0.20245744,
         -0.81668603, -0.81668603, -0.81668603, -0.81668603,
          0.69344074,  2.3564723 ]]], dtype=float32)

In [39]:
model.layer0[0].weight

Parameter containing:
tensor([[[ 0.0836, -0.1996, -0.0432],
         [-0.4023,  0.0570,  0.0549]],

        [[-0.0016,  0.3573,  0.3805],
         [-0.2461, -0.1395,  0.0413]],

        [[-0.2527,  0.0237, -0.1303],
         [-0.2319,  0.0021, -0.2924]],

        [[ 0.2583,  0.0774,  0.1887],
         [ 0.0946,  0.2593, -0.2539]]], device='cuda:0', requires_grad=True)

In [38]:
model.layer0[0].bias

Parameter containing:
tensor([ 0.3711, -0.2885, -0.3664, -0.3120], device='cuda:0',
       requires_grad=True)

In [36]:
model.save("BasicModelWeights")

In [58]:
model.layer4[2].weight

Parameter containing:
tensor([1., 1., 1., 1.], device='cuda:0', requires_grad=True)

In [56]:
model(input_feats)

tensor([[[ 0.4224, -0.9803, -1.2098,  1.2892, -0.2007, -1.1926,  1.1826,
          -0.4655, -1.2098, -0.7697,  1.2477,  0.6563, -0.3461,  1.5762],
         [-0.6300, -0.6300,  1.6054, -0.6300, -0.6300, -0.6300, -0.6300,
          -0.6300, -0.6300, -0.6300,  0.1536,  2.4050,  1.4039,  0.1019],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [-0.0514,  1.2775, -0.7956, -0.5920,  1.8553, -0.7956, -0.5470,
          -0.7956,  0.5707, -0.7956, -0.7956,  0.2434, -0.7956,  2.0171]]],
       device='cuda:0', grad_fn=<CudnnBatchNormBackward0>)
tensor([[[-0.4534, -0.4534,  0.1875, -0.4534, -0.4534, -0.4534, -0.4379,
          -0.4534, -0.4534,  3.2001, -0.0636,  0.2879],
         [-0.5221, -0.5221, -0.5221, -0.5221, -0.5221,  0.8218,  1.1191,
          -0.5221, -0.5221, -0.5221,  2.7579, -0.5221],
         [-0.8498,  2.2256, -1.0149, -1.1041,  0.4454, -0.6111, -1.1041,
           0.0522,  

c:\Users\chiny\OneDrive - Nanyang Technological University\Internships\AY24 DSO Summer\LegacyCNN\python_lib\BasicModel.py:77: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  z = F.softmax(y)


tensor([[0.1876, 0.1346, 0.0929, 0.3251, 0.1861, 0.0737]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)