In [1]:
from torchsummary import summary
from python_lib.BasicModel import BasicModel
import torch
import numpy as np
import os

In [2]:
model = BasicModel(input_size = 2, input_length = 16, out_features = 6).to("cuda")
# summary(model, (2,16))

# input_feats = torch.rand([10,2,16]).to("cuda")
# output = model(input_feats)
# output.shape

In [3]:
input_feats = torch.rand([1,2,16]).to("cuda")
input_feats_np = input_feats.cpu().detach().numpy()
input_feats_np = np.reshape(input_feats_np, (2,16))
print(input_feats_np)
dim = input_feats_np.shape

flatten_inputs = input_feats_np.flatten()
with open(os.path.join("BasicModelWeights", f"input.bin"), "wb") as f:
            # Write the dimensions down
            f.write(np.array(dim, dtype=np.int32).tobytes())
            # Write the flatten bias down
            f.write(flatten_inputs.tobytes())

[[0.21523035 0.14776528 0.28956282 0.92761934 0.7336509  0.8099116
  0.0805918  0.9454845  0.37772256 0.654699   0.23680395 0.13639969
  0.52952385 0.6869987  0.15913689 0.2564276 ]
 [0.02004808 0.43567842 0.85128176 0.5275597  0.5351463  0.41872543
  0.21224606 0.719749   0.943496   0.19102567 0.4625892  0.1721164
  0.13598078 0.00585544 0.42543107 0.09241921]]


In [4]:
model.layer0(input_feats).cpu().detach().numpy()

array([[[-0.15677316, -0.15677316, -0.15677316, -0.15677316,
         -0.15677316, -0.15677316, -0.15677316, -0.15677316,
         -0.15677316, -0.15677316, -0.15677316, -0.15677316,
         -0.15677316,  2.0380511 ],
        [-0.29988846,  3.584026  , -0.29988846, -0.29988846,
         -0.29988846, -0.29988846, -0.29988846, -0.29988846,
         -0.29988846, -0.29988846, -0.29988846,  0.01463531,
         -0.29988846, -0.29988846],
        [-0.4095652 , -0.45954415, -0.45954415, -0.45954415,
         -0.45954415,  1.5837413 , -0.45954415, -0.45954415,
         -0.45954415,  0.42619604, -0.45954415, -0.45954415,
         -0.45954415,  2.9950686 ],
        [ 1.2229835 ,  1.5427513 , -1.1987264 , -0.2772781 ,
         -1.1987264 ,  1.5714931 , -0.7436059 ,  0.15085906,
         -1.1987264 ,  0.14817654, -0.03210485,  0.11094227,
         -1.1987264 ,  1.100688  ]]], dtype=float32)

In [5]:
model.layer0[0].weight

Parameter containing:
tensor([[[ 0.2246, -0.3735, -0.2891],
         [-0.2223,  0.2639,  0.0954]],

        [[-0.2308, -0.3234,  0.3364],
         [-0.2648,  0.2037, -0.1495]],

        [[ 0.1703, -0.3840,  0.1195],
         [-0.3413, -0.0525, -0.1145]],

        [[ 0.0436, -0.3353,  0.3131],
         [-0.4048,  0.1789,  0.0357]]], device='cuda:0', requires_grad=True)

In [6]:
model.layer0[0].bias

Parameter containing:
tensor([-0.1321,  0.0039,  0.1151,  0.1811], device='cuda:0',
       requires_grad=True)

In [7]:
model.save("BasicModelWeights")

In [8]:
model(input_feats)

layer0 tensor([[[-0.1568, -0.1568, -0.1568, -0.1568, -0.1568, -0.1568, -0.1568,
          -0.1568, -0.1568, -0.1568, -0.1568, -0.1568, -0.1568,  2.0381],
         [-0.2999,  3.5840, -0.2999, -0.2999, -0.2999, -0.2999, -0.2999,
          -0.2999, -0.2999, -0.2999, -0.2999,  0.0146, -0.2999, -0.2999],
         [-0.4096, -0.4595, -0.4595, -0.4595, -0.4595,  1.5837, -0.4595,
          -0.4595, -0.4595,  0.4262, -0.4595, -0.4595, -0.4595,  2.9951],
         [ 1.2230,  1.5428, -1.1987, -0.2773, -1.1987,  1.5715, -0.7436,
           0.1509, -1.1987,  0.1482, -0.0321,  0.1109, -1.1987,  1.1007]]],
       device='cuda:0', grad_fn=<CudnnBatchNormBackward0>)
layer1 tensor([[[ 1.0551, -0.5976, -0.5976,  0.6229, -0.5976, -0.5976, -0.5976,
           0.3629, -0.5976, -0.5976, -0.5976,  2.7402],
         [ 0.2919, -0.3555, -0.3555, -0.3555, -0.3555, -0.3555, -0.3555,
          -0.3555, -0.3555, -0.3555, -0.3555,  3.2632],
         [ 0.3556,  2.6452, -0.8384, -0.2307, -0.8384,  0.3907, -0.8384,
      

c:\Users\chiny\OneDrive - Nanyang Technological University\Internships\AY24 DSO Summer\LegacyCNN\python_lib\BasicModel.py:77: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  z = F.softmax(y)


tensor([[0.1536, 0.1631, 0.2758, 0.1940, 0.0585, 0.1550]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)

In [9]:
print(model.layer3[0].weight)
print(model.layer3[0].bias)

Parameter containing:
tensor([[[ 0.1756,  0.2324, -0.0682],
         [-0.1006,  0.2525,  0.1080],
         [-0.2183,  0.1962,  0.1167],
         [-0.1462,  0.1314,  0.2332]],

        [[ 0.2478, -0.1032, -0.1953],
         [-0.1996,  0.1888, -0.1639],
         [ 0.1419,  0.2759,  0.1663],
         [-0.2215, -0.1677,  0.0983]],

        [[-0.0162, -0.1627, -0.0063],
         [ 0.1977,  0.0827,  0.0839],
         [-0.1529, -0.1014, -0.2197],
         [-0.0432, -0.2666,  0.2830]],

        [[-0.0920, -0.0870, -0.1693],
         [ 0.1423,  0.1242, -0.0449],
         [ 0.2883,  0.1416,  0.2420],
         [ 0.0011,  0.2182,  0.0726]]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.2089, 0.0918, 0.1198, 0.0153], device='cuda:0', requires_grad=True)


In [10]:
model.layer0

Sequential(
  (0): Conv1d(2, 4, kernel_size=(3,), stride=(1,))
  (1): ReLU(inplace=True)
  (2): BatchNorm1d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)