Import the necessary libraries and dependencies

In [11]:
from python_lib.modules import *
import torch
import numpy as np
import os
from python_lib.saveasfile import *

# Model initialisation 

Use BlockSave to save all the weights into a `.bin` file

Be sure to `load_state_dict` from a `.pt`/`.pth` file before BlockSave

It's omitted here as I don't have the weights on hand, so I just use a random initialised weights.

In [12]:
model = ECAPA_TDNN(input_size = 2, channels=[8,8,8,8,16], lin_neurons=6, device = "cuda").to("cuda")

BlockSave(model.return_layers(), "fullecapa", "ECAPAweights")

# Generate Input Feats for testing purposes

In [13]:
input_feats = torch.rand([100,2,64]).to("cuda")
input_feats_np = input_feats.cpu().detach().numpy()
input_feats_np = np.reshape(input_feats_np, (100,2,64))
print(input_feats_np)
dim = input_feats_np.shape
print(dim)

flatten_inputs = input_feats_np.flatten()
with open(os.path.join("ECAPAweights", f"ecapainput_2x64_100.bin"), "wb") as f:
            # Write the dimensions down
            f.write(np.array(dim, dtype=np.int32).tobytes())
            # Write the flatten bias down
            f.write(flatten_inputs.tobytes())

[[[0.34149832 0.37636566 0.62650234 ... 0.09052432 0.76767457 0.23272258]
  [0.53362054 0.48166353 0.79475635 ... 0.150886   0.7996159  0.12034094]]

 [[0.59842473 0.02847058 0.79718274 ... 0.46615368 0.30636483 0.58332264]
  [0.98534065 0.31697178 0.24182647 ... 0.93761045 0.45935005 0.7261669 ]]

 [[0.807831   0.09603226 0.5602161  ... 0.57906103 0.34993565 0.5375221 ]
  [0.8633781  0.68299186 0.06199419 ... 0.6680984  0.07415938 0.19900131]]

 ...

 [[0.32583755 0.31459486 0.6805412  ... 0.86272275 0.1265719  0.8649771 ]
  [0.21651435 0.44576806 0.20779884 ... 0.793362   0.30055386 0.28084207]]

 [[0.9380531  0.09069198 0.95391923 ... 0.12276822 0.9166646  0.08865559]
  [0.64113635 0.91034216 0.9125979  ... 0.22270381 0.29946    0.9769074 ]]

 [[0.03444189 0.2212426  0.73028284 ... 0.01019555 0.49794346 0.35037827]
  [0.4887898  0.04597694 0.7009779  ... 0.20657468 0.55839556 0.7299678 ]]]
(100, 2, 64)


# Run the model using eval/train mode

In [14]:
model.eval()

model(input_feats)

tensor([[0.1682, 0.1453, 0.1962, 0.1661, 0.1516, 0.1725],
        [0.1683, 0.1452, 0.1959, 0.1658, 0.1515, 0.1734],
        [0.1680, 0.1452, 0.1958, 0.1662, 0.1516, 0.1731],
        [0.1679, 0.1454, 0.1956, 0.1661, 0.1515, 0.1735],
        [0.1684, 0.1451, 0.1968, 0.1660, 0.1519, 0.1718],
        [0.1680, 0.1453, 0.1959, 0.1663, 0.1516, 0.1729],
        [0.1679, 0.1453, 0.1961, 0.1664, 0.1517, 0.1727],
        [0.1679, 0.1451, 0.1964, 0.1663, 0.1518, 0.1725],
        [0.1681, 0.1453, 0.1961, 0.1661, 0.1516, 0.1728],
        [0.1687, 0.1448, 0.1972, 0.1654, 0.1518, 0.1720],
        [0.1686, 0.1450, 0.1968, 0.1654, 0.1517, 0.1724],
        [0.1680, 0.1452, 0.1962, 0.1663, 0.1518, 0.1725],
        [0.1677, 0.1455, 0.1953, 0.1665, 0.1515, 0.1736],
        [0.1682, 0.1450, 0.1966, 0.1662, 0.1519, 0.1720],
        [0.1686, 0.1448, 0.1971, 0.1658, 0.1519, 0.1717],
        [0.1689, 0.1447, 0.1973, 0.1654, 0.1519, 0.1719],
        [0.1682, 0.1449, 0.1973, 0.1659, 0.1519, 0.1717],
        [0.169