In [1]:
import torch

In [2]:
data = torch.randn((2,16))
data

tensor([[ 1.2374,  0.7530, -1.6983, -0.5301, -1.3627, -0.5893,  1.1252, -1.7811,
         -0.1937, -0.7634, -1.5650, -1.3295,  0.4027,  0.3593, -0.4867, -0.1175],
        [ 0.4844, -0.2681, -1.5219,  0.3690, -1.7322, -0.5980, -0.5738,  1.1502,
         -0.5947, -1.4961, -0.7994, -0.6638, -1.8650,  1.6413, -0.1663,  1.5513]])

In [10]:
d2 = torch.chunk(data, 6, dim= 1)
d2

(tensor([[ 1.2374,  0.7530, -1.6983],
         [ 0.4844, -0.2681, -1.5219]]),
 tensor([[-0.5301, -1.3627, -0.5893],
         [ 0.3690, -1.7322, -0.5980]]),
 tensor([[ 1.1252, -1.7811, -0.1937],
         [-0.5738,  1.1502, -0.5947]]),
 tensor([[-0.7634, -1.5650, -1.3295],
         [-1.4961, -0.7994, -0.6638]]),
 tensor([[ 0.4027,  0.3593, -0.4867],
         [-1.8650,  1.6413, -0.1663]]),
 tensor([[-0.1175],
         [ 1.5513]]))

In [11]:
torch.cat(d2, dim = 1)

tensor([[ 1.2374,  0.7530, -1.6983, -0.5301, -1.3627, -0.5893,  1.1252, -1.7811,
         -0.1937, -0.7634, -1.5650, -1.3295,  0.4027,  0.3593, -0.4867, -0.1175],
        [ 0.4844, -0.2681, -1.5219,  0.3690, -1.7322, -0.5980, -0.5738,  1.1502,
         -0.5947, -1.4961, -0.7994, -0.6638, -1.8650,  1.6413, -0.1663,  1.5513]])